version: '3'
services:
  db:
    image: mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: Password
      MYSQL_DATABASE: yourls
      MYSQL_USER: yourls
      MYSQL_PASSWORD: Password
    volumes:
      - ./db:/var/lib/mysql

  yourls:
    container_name: some-yourls
    links:
      - db
    depends_on:
      - db
    ports:
      - 8183:80
    environment:
      - YOURLS_SITE=https://yoururrl.com
      - YOURLS_USER=USERNAME
      - YOURLS_PASS=Password
      - YOURLS_DB_HOST=db
      - YOURLS_DB_USER=yourls
      - YOURLS_DB_PASS=Password
    image: yourls
    volumes:
      - ./data:/var/www/html/user

volumes:
  db_data:
  yourls_data:
